new change

diff --git a/.github/workflows/move-code-2-prod.yaml b/.github/workflows/move-code-2-prod.yaml
--- a/.github/workflows/move-code-2-prod.yaml
+++ b/.github/workflows/move-code-2-prod.yaml
@@ -3,21 +3,9 @@ name: Copy Files within Main Branch
 on:
   workflow_dispatch:
     inputs:
-      extraVars:
-        description: 'extraVars'
+      option:
+        description: 'Choose an option (extraVars, inventory, deploymentManifest)'
         required: true
-        paths: |
-          main/non-prod/dedicated/extraVars/
-      inventory:
-        description: 'inventory'
-        required: true
-        paths: |
-          main/non-prod/dedicated/inventory/
-      deploymentManifest:
-        description: 'deploymentManifest'
-        required: true
-        paths: |
-          main/non-prod/dedicated/deploymentManifest/
 
 jobs:
   copy_files:
@@ -28,14 +16,21 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      # Copy files based on selected options
-      - name: Copy Files
+      - name: Copy Files based on option
         run: |
-          IFS=',' read -ra extraVars <<< "${{ github.event.inputs.extraVars }}"
-          IFS=',' read -ra inventory <<< "${{ github.event.inputs.inventory }}"
-          IFS=',' read -ra deploymentManifest <<< "${{ github.event.inputs.deploymentManifest }}"
-          for source in "${extraVars[@]}" "${inventory[@]}" "${deploymentManifest[@]}"; do
-            destination="main/prod/dedicated/${source#main/non-prod/dedicated/}"
-            echo "Copying files from $source to $destination"
-            cp -r "${{ github.workspace }}/$source/"* "${{ github.workspace }}/$destination"
-          done
+          option="${{ github.event.inputs.option }}"
+          case $option in
+            extraVars)
+              cp -R main/non-prod/dedicated/extraVars/* main/prod/dedicated/extraVars/
+              ;;
+            inventory)
+              cp -R main/non-prod/dedicated/inventory/* main/prod/dedicated/inventory/
+              ;;
+            deploymentManifest)
+              cp -R main/non-prod/dedicated/deploymentManifest/* main/prod/dedicated/deploymentManifest/
+              ;;
+            *)
+              echo "Invalid option selected."
+              exit 1
+              ;;
+          esac
